version: "3"

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 5525
      POSTGRES_USER: postgres
      POSTGRES_DB: "todoListBase"
    ports:
      - 5432:5432

  backend:
    build: BackEnd/
    restart: always
    ports:
      - 3001:3001
    environment:
      HOSTNAME: db
    depends_on:
      - db
    links:
      - db

  frontend:
    build: vueNuxt/
    restart: always
    ports:
      - 3000:3000
